{
  "openapi": "3.0.0",
  "info": {
    "title": "Fraud Prevention API",
    "version": "1.0.0",
    "description": "Provides detailed information about email addresses and their risk and fraud correlation.",
    "contact": {
      "email": "emailexperts@atdata.com"
    }
  },
  "servers": [
    {
      "url": "https://api.atdata.com"
    }
  ],
  "paths": {
    "/fr": {
      "get": {
        "operationId": "retrieve-fraud-risk",
        "description": "Retrieves fraud risk information based on the provided email and optional personal data.",
        "summary": "Fraud Prevention",
        "parameters": [
          {
            "in": "query",
            "name": "api_key",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "API key for accessing the service.",
            "example": "<YOUR_API_KEY>"
          },
          {
            "in": "query",
            "name": "email",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The email address to be evaluated for fraud.",
            "example": "example@atdata.com"
          },
          {
            "in": "query",
            "name": "reference_id",
            "schema": {
              "type": "string"
            },
            "description": "Internal identifier for the email or transaction.",
            "example": "a4840850-98be-46de-b391-3d52732d27c4"
          },
          {
            "in": "query",
            "name": "first",
            "schema": {
              "type": "string"
            },
            "description": "First name of the individual.",
            "example": "Joe"
          },
          {
            "in": "query",
            "name": "last",
            "schema": {
              "type": "string"
            },
            "description": "Last name of the individual.",
            "example": "Bloggs"
          },
          {
            "in": "query",
            "name": "street",
            "schema": {
              "type": "string"
            },
            "description": "First line of the postal address, including number.",
            "example": "123 Main St"
          },
          {
            "in": "query",
            "name": "city",
            "schema": {
              "type": "string"
            },
            "description": "City of the postal address.",
            "example": "New York"
          },
          {
            "in": "query",
            "name": "state",
            "schema": {
              "type": "string"
            },
            "description": "State of the postal address.",
            "example": "NY"
          },
          {
            "in": "query",
            "name": "zip",
            "schema": {
              "type": "string"
            },
            "description": "ZIP or postcode of the postal address.",
            "example": 38067
          },
          {
            "in": "query",
            "name": "country",
            "schema": {
              "type": "string"
            },
            "description": "2 letter country code, [ISO 3166 standard alpha-2 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).",
            "example": "US"
          },
          {
            "in": "query",
            "name": "phone",
            "schema": {
              "type": "string"
            },
            "description": "Phone number, including country code.",
            "example": "16467421771"
          },
          {
            "in": "query",
            "name": "ip",
            "schema": {
              "type": "string"
            },
            "description": "User's IP address.",
            "example": "65.49.22.28"
          },
          {
            "in": "query",
            "name": "user_agent",
            "schema": {
              "type": "string"
            },
            "description": "User agent of the client.",
            "example": "Mozilla/5.0"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FraudRetrieveResponse"
                },
                "examples": {
                  "example1": {
                    "summary": "Success",
                    "value": {
                      "eam": {
                        "longevity": 2,
                        "velocity": 4,
                        "date_first_seen": "2017-04-21",
                        "popularity": 1
                      },
                      "dam": {
                        "longevity": 3,
                        "velocity": 6,
                        "date_first_seen": "2017-04-21",
                        "popularity": 5
                      },
                      "risk": {
                        "score": 94,
                        "query_id": "47b1b085-1ced-4697-8fba-cb98db09709d",
                        "tumbling_risk": 0,
                        "ip": {
                          "routing_type": "fixed",
                          "organization": "samsungsds inc.",
                          "latitude": 37.561,
                          "proxy_type": "",
                          "hosting_facility": false,
                          "longitude": 126.98265
                        },
                        "domain_risk_score": 0,
                        "postal": {
                          "deliverability": "deliverable",
                          "address_type": "Street",
                          "last_name_match": "match",
                          "first_name_match": "no_match",
                          "deliverability_substatus": "deliverable",
                          "zip_match": "no_match",
                          "city_match": "match",
                          "street_match": "no_match"
                        },
                        "phone": {
                          "line_type": "mobile",
                          "carrier": "AT&T Wireless",
                          "status": "live",
                          "prepaid": false,
                          "owner": {
                            "first_name_match": "match",
                            "last_name_match": "match",
                            "street_match": "match",
                            "city_match": "match",
                            "zip_match": "match",
                            "type": "person"
                          }
                        }
                      },
                      "email_validation": {
                        "domain_type": "biz",
                        "status_code": 50,
                        "address": "example@atdata.com",
                        "status": "valid"
                      }
                    }
                  },
                  "example2": {
                    "summary": "Invalid postal address",
                    "value": {
                      "eam": {
                        "longevity": 1,
                        "velocity": 0,
                        "date_first_seen": "2024-05-13",
                        "popularity": 0
                      },
                      "dam": {
                        "longevity": 2,
                        "velocity": 0,
                        "date_first_seen": "2024-02-15",
                        "popularity": 0
                      },
                      "risk": {
                        "score": 99,
                        "query_id": "bf08e205-f413-43ef-ad17-1342ede71925",
                        "tumbling_risk": 0,
                        "domain": {
                          "domain_risk_score": 10
                        },
                        "postal": {
                          "deliverability": "undeliverable",
                          "last_name_match": "no_data",
                          "first_name_match": "no_data",
                          "deliverability_substatus": "invalid_street",
                          "zip_match": "no_data",
                          "city_match": "no_data",
                          "street_match": "no_data"
                        }
                      },
                      "email_validation": {
                        "status_code": 50,
                        "address": "example@atdata.com",
                        "status": "valid"
                      }
                    }
                  },
                  "example3": {
                    "summary": "Email Only",
                    "value": {
                      "eam": {
                        "longevity": 3,
                        "velocity": 0,
                        "date_first_seen": "2011-04-04",
                        "popularity": 0
                      },
                      "dam": {
                        "longevity": 3,
                        "velocity": 10,
                        "date_first_seen": "2002-11-09",
                        "popularity": 10
                      },
                      "risk": {
                        "score": 1,
                        "query_id": "9aef8719-e1cf-4a1e-afea-9e2764b716d0",
                        "tumbling_risk": 0,
                        "domain": {
                          "domain_risk_score": 0
                        }
                      },
                      "email_validation": {
                        "domain_type": "freeisp",
                        "status_code": 50,
                        "address": "example@atdata.com",
                        "status": "valid"
                      }
                    }
                  },
                  "example4": {
                    "summary": "Incorrectly typed email",
                    "value": {
                      "email_validation": {
                        "status_code": 115,
                        "address": "example@atdata",
                        "role_account": true,
                        "email_corrections": [
                          "example@atdata.com"
                        ],
                        "status": "invalid"
                      }
                    }
                  },
                  "example5": {
                    "summary": "Invalid email",
                    "value": {
                      "email_validation": {
                        "status_code": 150,
                        "address": "notanactualemail",
                        "status": "invalid"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/schemas/BadRequest400",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string",
                  "example": "Missing query parameter(s)."
                },
                "examples": {
                  "example1": {
                    "summary": "Missing email",
                    "value": "Missing query parameter(s)."
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/schemas/Unauthorized401",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string",
                  "example": "Invalid API key."
                },
                "examples": {
                  "example1": {
                    "summary": "Invalid API key",
                    "value": "Invalid API key."
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "FraudRetrieveResponse": {
        "type": "object",
        "properties": {
          "risk": {
            "type": "object",
            "description": "Risk related data for the given query based on the provided email and associated details.",
            "properties": {
              "score": {
                "type": "integer",
                "description": "A machine learning-based score from 0 to 100 that assesses the risk associated with the email, with higher scores indicating higher risk.",
                "example": 50
              },
              "tumbling_risk": {
                "type": "integer",
                "description": "A score from 0 to 3 indicating the presence of multiple variations of the same email address, with higher scores indicating more variations detected.",
                "example": 0
              },
              "query_id": {
                "type": "string",
                "description": "Unique identifier for the response provided. Can be used with our [Feedback API](https://atdata-fraud.readme.io/reference/submit-feedback) or for troubleshooting.",
                "example": "2744dd5d0acb475b81687d366fff4c48"
              },
              "ip": {
                "type": "object",
                "description": "Details about the IP address associated with the email query, providing insights into the location and network characteristics.",
                "properties": {
                  "routing_type": {
                    "type": "string",
                    "description": "Specifies how the connection is routed through the Internet, which can indicate the proximity of the user to the public IP address.",
                    "example": "fixed"
                  },
                  "organization": {
                    "type": "string",
                    "description": "Name of the organization managing the IP, often indicating the type of entity, such as a corporation, government, or educational institution.",
                    "example": "atdata"
                  },
                  "proxy_type": {
                    "type": "string",
                    "description": "Type of proxy used, if any, providing insights into the anonymity or masking techniques that may be employed.",
                    "example": "tor"
                  },
                  "hosting_facility": {
                    "type": "boolean",
                    "description": "Indicates whether the IP address is associated with a hosting facility, which can suggest usage by cloud services or data centers.",
                    "example": true
                  },
                  "latitude": {
                    "type": "number",
                    "format": "double",
                    "description": "Geographical latitude of the identified IP location, expressed as a floating point number with range of -90 to 90, with positive numbers representing North and negative numbers representing South.",
                    "example": 38.89768
                  },
                  "longitude": {
                    "type": "number",
                    "format": "double",
                    "description": "Geographical longitude of the identified IP location, expressed as a floating point number with range of -180 to 180, with positive numbers representing East and negative numbers representing West.",
                    "example": -77.03651
                  }
                }
              },
              "domain_risk_score": {
                "type": "integer",
                "description": "A score from 0 to 10 assessing the risk associated with the email domain, with higher scores indicating higher risk.",
                "example": 5
              },
              "postal": {
                "type": "object",
                "description": "Details about the postal information provided in the query and its correlation with the email address data.",
                "properties": {
                  "first_name_match": {
                    "type": "string",
                    "description": "Indicates if the provided first name matches records associated with the email.",
                    "example": "match"
                  },
                  "last_name_match": {
                    "type": "string",
                    "description": "Indicates if the provided last name matches records associated with the email.",
                    "example": "no_match"
                  },
                  "street_match": {
                    "type": "string",
                    "description": "Indicates if the provided street address matches records associated with the email.",
                    "example": "no_data"
                  },
                  "city_match": {
                    "type": "string",
                    "description": "Indicates if the provided city matches records associated with the email.",
                    "example": "no_data"
                  },
                  "zip_match": {
                    "type": "string",
                    "description": "Indicates if the provided zip code matches records associated with the email.",
                    "example": "no_data"
                  },
                  "deliverability": {
                    "type": "string",
                    "description": "Indicates the deliverability status of the postal address as determined by postal services.",
                    "example": "undeliverable"
                  },
                  "deliverability_substatus": {
                    "type": "string",
                    "description": "Provides further details on the primary reason for the deliverability status.",
                    "example": "missing_primary"
                  },
                  "address_type": {
                    "type": "string",
                    "description": "Describes the type of the address provided, such as Street, PO Box, Rural Route, etc.",
                    "example": "Street"
                  }
                }
              },
              "phone": {
                "type": "object",
                "description": "Details about the phone number information provided in the query and its correlation with the email address data.",
                "properties": {
                  "line_type": {
                    "type": "string",
                    "description": "The type of the phone line (e.g., mobile, landline).",
                    "example": "mobile"
                  },
                  "carrier": {
                    "type": "string",
                    "description": "The carrier or service provider of the phone number.",
                    "example": "AT&T Wireless"
                  },
                  "status": {
                    "type": "string",
                    "description": "The current status of the phone number (e.g., live, disconnected).",
                    "example": "live"
                  },
                  "prepaid": {
                    "type": "boolean",
                    "description": "Indicates if the phone number is prepaid.",
                    "example": false
                  },
                  "owner": {
                    "type": "object",
                    "description": "Information about the owner of the phone number.",
                    "properties": {
                      "first_name_match": {
                        "type": "string",
                        "description": "Indicates if the provided first name matches the owner's first name.",
                        "example": "match"
                      },
                      "last_name_match": {
                        "type": "string",
                        "description": "Indicates if the provided last name matches the owner's last name.",
                        "example": "match"
                      },
                      "street_match": {
                        "type": "string",
                        "description": "Indicates if the provided street address matches the owner's street address.",
                        "example": "match"
                      },
                      "city_match": {
                        "type": "string",
                        "description": "Indicates if the provided city matches the owner's city.",
                        "example": "match"
                      },
                      "zip_match": {
                        "type": "string",
                        "description": "Indicates if the provided ZIP code matches the owner's ZIP code.",
                        "example": "match"
                      },
                      "type": {
                        "type": "string",
                        "description": "The type of the owner (e.g., person, business).",
                        "example": "person"
                      }
                    }
                  }
                }
              }
            }
          },
          "eam": {
            "type": "object",
            "description": "Email Activity Metrics, which evaluate the history and usage patterns of the email address.",
            "properties": {
              "date_first_seen": {
                "type": "string",
                "format": "date",
                "description": "The first date the email address was observed by AtData's systems.",
                "example": "2016-08-09"
              },
              "longevity": {
                "type": "integer",
                "description": "A score from 0 to 3 indicating how long the email address has been known, with higher values indicating a longer history.",
                "example": 3
              },
              "velocity": {
                "type": "integer",
                "description": "A score from 0 to 10 reflecting the activity level of the email address over recent months, with higher scores indicating more activity.",
                "example": 10
              },
              "popularity": {
                "type": "integer",
                "description": "A score from 0 to 10 gauging the email address's exposure across different sources and networks, with higher scores indicating wider recognition.",
                "example": 10
              }
            }
          },
          "dam": {
            "type": "object",
            "description": "Domain Activity Metrics, reflecting activity at the domain level rather than individual email addresses.",
            "properties": {
              "date_first_seen": {
                "type": "string",
                "format": "date",
                "description": "The first date the domain was observed in AtData's records.",
                "example": "2002-11-09"
              },
              "longevity": {
                "type": "integer",
                "description": "A score from 0 to 3 indicating when AtData first encountered the domain, with higher values indicating a longer recognition.",
                "example": 3
              },
              "velocity": {
                "type": "integer",
                "description": "A score reflecting the activity of the domain over the last six months, from 0 (no activity) to 10 (most active).",
                "example": 10
              },
              "popularity": {
                "type": "integer",
                "description": "A score gauging the popularity of the domain over the last year based on the number of sources from which AtData has received the domain.",
                "example": 10
              }
            }
          },
          "email_validation": {
            "type": "object",
            "description": "Validation results for the queried email address, assessing its validity for sending emails.",
            "properties": {
              "status": {
                "type": "string",
                "description": "The overall status of the email validation attempt, indicating if the email is valid, invalid, risky, or unknown.",
                "example": "valid"
              },
              "status_code": {
                "type": "integer",
                "description": "A detailed status code providing more specific results of the email validation. For a full list of possible values, go to the [Email Validation Status Codes](/page/status-codes) page.",
                "example": 50
              },
              "domain_type": {
                "type": "string",
                "description": "Type of the domain of the email address, such as free ISP, disposable, corporate, etc.",
                "example": "freeisp"
              }
            }
          }
        }
      },
      "BadRequest400": {
        "description": "Bad request: Either an invalid parameter exists or the data expected is not present."
      },
      "Unauthorized401": {
        "description": "Unauthorized: Check you're using the right api_key."
      }
    }
  }
}